import { IMPOSSIBLE, VersionInfo } from '@start9labs/start-sdk'

export const current = VersionInfo.of({
  version: '1.0.3:0',
  releaseNotes: {
    en_US: `BitcoinTX 1.0.3: AI assistants now use an AI key instead of your password. In BitcoinTX, Settings > Connect an AI Assistant, turn on AI access and create a key (it is shown once), then paste it into your AI app's settings. The key can read your ledger, add or change entries and make a backup; it can't log in, change your password, restore or delete everything, and you can revoke it there. The Connect an AI Assistant action no longer shows your login, and the AI connector now updates itself when your AI app restarts. If you already use an AI app with BitcoinTX: in its settings, replace BTCTX_USERNAME and BTCTX_PASSWORD with BTCTX_AI_KEY, then run Reset Login Credentials (or change your password in BitcoinTX), because the old one sat in that file.`,
    es_ES: `BitcoinTX 1.0.3: los asistentes de IA usan ahora una clave de IA en lugar de tu contraseña. En BitcoinTX, en Settings > Connect an AI Assistant, activa el acceso de IA y crea una clave (se muestra una sola vez); después pégala en la configuración de tu aplicación de IA. La clave puede leer tu libro contable, añadir o cambiar registros y hacer una copia de seguridad; no puede iniciar sesión, cambiar tu contraseña, restaurar ni borrarlo todo, y puedes revocarla allí mismo. La acción Connect an AI Assistant ya no muestra tus credenciales, y el conector de IA se actualiza solo cuando reinicias tu aplicación de IA. Si ya usas una aplicación de IA con BitcoinTX: en su configuración, sustituye BTCTX_USERNAME y BTCTX_PASSWORD por BTCTX_AI_KEY y después ejecuta Reset Login Credentials (o cambia tu contraseña en BitcoinTX), porque la anterior estaba guardada en ese archivo.`,
    de_DE: `BitcoinTX 1.0.3: KI-Assistenten verwenden jetzt einen KI-Schlüssel statt deines Passworts. Schalte in BitcoinTX unter Settings > Connect an AI Assistant den KI-Zugriff ein und erstelle einen Schlüssel (er wird nur einmal angezeigt); füge ihn dann in die Einstellungen deiner KI-App ein. Der Schlüssel kann dein Journal lesen, Einträge hinzufügen oder ändern und eine Sicherung anlegen; er kann sich nicht anmelden, dein Passwort nicht ändern, nichts wiederherstellen und nicht alles löschen, und du kannst ihn dort widerrufen. Die Aktion Connect an AI Assistant zeigt deine Zugangsdaten nicht mehr an, und der KI-Connector aktualisiert sich beim Neustart deiner KI-App selbst. Wenn du BitcoinTX schon mit einer KI-App nutzt: Ersetze in deren Einstellungen BTCTX_USERNAME und BTCTX_PASSWORD durch BTCTX_AI_KEY und führe dann Reset Login Credentials aus (oder ändere dein Passwort in BitcoinTX), denn das alte stand in dieser Datei.`,
    pl_PL: `BitcoinTX 1.0.3: asystenci AI używają teraz klucza AI zamiast Twojego hasła. W BitcoinTX, w Settings > Connect an AI Assistant, włącz dostęp AI i utwórz klucz (jest pokazywany tylko raz), a potem wklej go do ustawień swojej aplikacji AI. Klucz może odczytywać Twoją księgę, dodawać lub zmieniać wpisy i tworzyć kopię zapasową; nie może się logować, zmieniać hasła, przywracać kopii ani usuwać wszystkiego, a możesz go tam unieważnić. Akcja Connect an AI Assistant nie pokazuje już Twoich danych logowania, a konektor AI aktualizuje się sam po ponownym uruchomieniu aplikacji AI. Jeśli już używasz aplikacji AI z BitcoinTX: w jej ustawieniach zastąp BTCTX_USERNAME i BTCTX_PASSWORD przez BTCTX_AI_KEY, a następnie uruchom Reset Login Credentials (albo zmień hasło w BitcoinTX), bo stare było zapisane w tym pliku.`,
    fr_FR: `BitcoinTX 1.0.3 : les assistants IA utilisent désormais une clé IA au lieu de votre mot de passe. Dans BitcoinTX, sous Settings > Connect an AI Assistant, activez l’accès IA et créez une clé (affichée une seule fois), puis collez-la dans les réglages de votre application d’IA. La clé peut lire votre registre, ajouter ou modifier des écritures et faire une sauvegarde ; elle ne peut pas se connecter, changer votre mot de passe, restaurer ni tout supprimer, et vous pouvez la révoquer au même endroit. L’action Connect an AI Assistant n’affiche plus vos identifiants, et le connecteur IA se met à jour tout seul au redémarrage de votre application d’IA. Si vous utilisez déjà une application d’IA avec BitcoinTX : dans ses réglages, remplacez BTCTX_USERNAME et BTCTX_PASSWORD par BTCTX_AI_KEY, puis lancez Reset Login Credentials (ou changez votre mot de passe dans BitcoinTX), car l’ancien se trouvait dans ce fichier.`,
  },
  migrations: {
    up: async () => {},
    down: IMPOSSIBLE,
  },
})
