import { IMPOSSIBLE, VersionInfo } from '@start9labs/start-sdk'

const CHANGELOG =
  'https://github.com/DigiMonk73/BTCTX-MCP/blob/main/docs/CHANGELOG.md'

/** 1.2.4:0: fixes from testing 1.2.3 and the unused lock removed (the app migrates its database to schema 0005); nothing for the package to migrate. */
export const current = VersionInfo.of({
  version: '1.2.4:0',
  releaseNotes: {
    en_US: `BitcoinTX 1.2.4 brings small fixes found by testing 1.2.3, with no change to any tax figure. A CSV export imported again now keeps a fee of 0 as 0 instead of dropping it. On a phone, every tab in the top bar fits on screen, Logout included. Escape closes the panel for adding or editing a transaction, asking first if you have unsaved changes. An unused transaction lock that nothing could switch on was removed; this updates the database once (a copy of it is kept first). Coming from 1.2.1 or earlier? You also get 1.2.2's tax-figure fixes and 1.2.3's code cleanup: after updating, open Settings > Ledger Review in BitcoinTX, and if it lists figures a recalculation would change, run Recalculate Ledger. Everything: ${CHANGELOG}`,
    es_ES: `BitcoinTX 1.2.4 trae pequeñas correcciones encontradas al probar la 1.2.3, sin cambiar ninguna cifra fiscal. Un CSV exportado e importado de nuevo ahora conserva una comisión de 0 como 0 en lugar de eliminarla. En un teléfono, todas las pestañas de la barra superior caben en la pantalla, incluido Logout. La tecla Escape cierra el panel para añadir o editar una transacción, preguntando antes si tienes cambios sin guardar. Se eliminó un bloqueo de transacciones sin uso que nada podía activar; esto actualiza la base de datos una vez (antes se guarda una copia). ¿Vienes de la 1.2.1 o anterior? También recibes las correcciones de cifras fiscales de la 1.2.2 y la reorganización del código de la 1.2.3: tras actualizar, abre Settings > Ledger Review en BitcoinTX y, si muestra cifras que un recálculo cambiaría, ejecuta Recalcular el libro contable. Todo: ${CHANGELOG}`,
    de_DE: `BitcoinTX 1.2.4 bringt kleine Korrekturen aus den Tests von 1.2.3, ohne eine Steuerzahl zu ändern. Eine exportierte und wieder importierte CSV behält eine Gebühr von 0 jetzt als 0, statt sie wegzulassen. Auf dem Handy passen alle Reiter der oberen Leiste auf den Bildschirm, Logout eingeschlossen. Die Escape-Taste schließt das Feld zum Hinzufügen oder Bearbeiten einer Transaktion und fragt vorher, wenn du ungespeicherte Änderungen hast. Eine ungenutzte Sperre für Transaktionen, die nichts einschalten konnte, wurde entfernt; dafür wird die Datenbank einmal aktualisiert (vorher wird eine Kopie gesichert). Du kommst von 1.2.1 oder älter? Dann erhältst du auch die Korrekturen der Steuerzahlen aus 1.2.2 und die Code-Neuordnung aus 1.2.3: Öffne nach dem Update Settings > Ledger Review in BitcoinTX, und listet es Zahlen, die eine Neuberechnung ändern würde, führe Journal neu berechnen aus. Alles: ${CHANGELOG}`,
    pl_PL: `BitcoinTX 1.2.4 przynosi drobne poprawki znalezione podczas testów 1.2.3, bez zmiany żadnej wartości podatkowej. Wyeksportowany i ponownie zaimportowany plik CSV zachowuje teraz opłatę 0 jako 0, zamiast ją pomijać. Na telefonie wszystkie karty górnego paska mieszczą się na ekranie, łącznie z Logout. Klawisz Escape zamyka panel dodawania lub edycji transakcji, a jeśli masz niezapisane zmiany, najpierw pyta. Usunięto nieużywaną blokadę transakcji, której nic nie mogło włączyć; wymaga to jednorazowej aktualizacji bazy danych (wcześniej zapisywana jest jej kopia). Aktualizujesz z 1.2.1 lub starszej wersji? Otrzymujesz też poprawki wartości podatkowych z 1.2.2 i uporządkowanie kodu z 1.2.3: po aktualizacji otwórz Settings > Ledger Review w BitcoinTX, a jeśli pokazuje wartości, które zmieniłoby przeliczenie, uruchom Przelicz księgę. Wszystko: ${CHANGELOG}`,
    fr_FR: `BitcoinTX 1.2.4 apporte de petites corrections trouvées en testant la 1.2.3, sans changer aucun chiffre fiscal. Un CSV exporté puis réimporté conserve désormais des frais de 0 comme 0 au lieu de les supprimer. Sur un téléphone, tous les onglets de la barre du haut tiennent à l’écran, Logout compris. La touche Échap ferme le panneau d’ajout ou de modification d’une transaction, en demandant d’abord si vous avez des modifications non enregistrées. Un verrou de transaction inutilisé, que rien ne pouvait activer, a été retiré ; la base de données est mise à jour une fois pour cela (une copie en est gardée avant). Vous venez de la 1.2.1 ou d’une version antérieure ? Vous recevez aussi les corrections de chiffres fiscaux de la 1.2.2 et la réorganisation du code de la 1.2.3 : après la mise à jour, ouvrez Settings > Ledger Review dans BitcoinTX et, s’il liste des chiffres qu’un recalcul changerait, lancez Recalculer le registre. Tout : ${CHANGELOG}`,
  },
  migrations: {
    up: async () => {},
    down: IMPOSSIBLE,
  },
})
