import { IMPOSSIBLE, VersionInfo } from '@start9labs/start-sdk'

const CHANGELOG =
  'https://github.com/DigiMonk73/BTCTX-MCP/blob/main/docs/CHANGELOG.md'

export const current = VersionInfo.of({
  version: '1.1.0:0',
  releaseNotes: {
    en_US: `BitcoinTX 1.1.0: you choose where Bitcoin prices come from, and nothing is contacted until you do. Right after logging in, pick My mempool server, Public price sites or Off (Settings > Privacy & Network). Your own mempool now also gives past prices, and public sites are asked only if you turn on the fallback. Past-price lookups no longer reveal your transaction dates. Reports can no longer be made to fetch outside addresses, logins are rate-limited, and new passwords need 12 characters. A mempool address starting with https (such as the .local ones) doesn't work yet: for now, turn on Fall back to public price sites. Everything: ${CHANGELOG}`,
    es_ES: `BitcoinTX 1.1.0: tú eliges de dónde vienen los precios de bitcoin, y no se contacta nada hasta que lo hagas. Justo después de iniciar sesión, elige My mempool server, Public price sites u Off (Settings > Privacy & Network). Tu propio mempool ahora también da precios pasados, y los sitios públicos solo se consultan si activas la alternativa (fallback). Las consultas de precios pasados ya no revelan las fechas de tus transacciones. Los informes ya no pueden hacer que se contacten direcciones externas, los inicios de sesión tienen un límite de intentos y las contraseñas nuevas necesitan 12 caracteres. Una dirección de mempool que empieza por https (como las .local) todavía no funciona: por ahora, activa Fall back to public price sites. Todo: ${CHANGELOG}`,
    de_DE: `BitcoinTX 1.1.0: Du wählst, woher die Bitcoin-Kurse kommen, und bis dahin wird nichts kontaktiert. Wähle direkt nach der Anmeldung My mempool server, Public price sites oder Off (Settings > Privacy & Network). Dein eigener mempool liefert jetzt auch vergangene Kurse, und öffentliche Seiten werden nur gefragt, wenn du den Fallback einschaltest. Abfragen vergangener Kurse verraten keine Transaktionsdaten mehr. Berichte können keine externen Adressen mehr abrufen lassen, Anmeldeversuche werden gebremst, und neue Passwörter brauchen 12 Zeichen. Eine mempool-Adresse mit https (wie die .local-Adressen) funktioniert noch nicht: Schalte vorerst Fall back to public price sites ein. Alles: ${CHANGELOG}`,
    pl_PL: `BitcoinTX 1.1.0: sam wybierasz, skąd pochodzą ceny bitcoina, a do tego czasu nic nie jest kontaktowane. Zaraz po zalogowaniu wybierz My mempool server, Public price sites albo Off (Settings > Privacy & Network). Twój własny mempool podaje teraz też ceny historyczne, a strony publiczne są pytane tylko wtedy, gdy włączysz fallback. Zapytania o ceny historyczne nie ujawniają już dat Twoich transakcji. Raporty nie mogą już pobierać zewnętrznych adresów, próby logowania są ograniczane, a nowe hasła muszą mieć 12 znaków. Adres mempool zaczynający się od https (np. adresy .local) jeszcze nie działa: na razie włącz Fall back to public price sites. Wszystko: ${CHANGELOG}`,
    fr_FR: `BitcoinTX 1.1.0 : vous choisissez d’où viennent les prix du bitcoin, et rien n’est contacté avant votre choix. Juste après la connexion, choisissez My mempool server, Public price sites ou Off (Settings > Privacy & Network). Votre propre mempool fournit désormais aussi les prix passés, et les sites publics ne sont interrogés que si vous activez le repli (fallback). Les recherches de prix passés ne révèlent plus les dates de vos transactions. Les rapports ne peuvent plus faire contacter d’adresses extérieures, les connexions sont limitées et les nouveaux mots de passe demandent 12 caractères. Une adresse mempool en https (comme les adresses .local) ne fonctionne pas encore : activez pour l’instant Fall back to public price sites. Tout : ${CHANGELOG}`,
  },
  migrations: {
    up: async () => {},
    down: IMPOSSIBLE,
  },
})
